### ISSUE TITLE
Wrong path to plugin-install.php on subdir installation

### ISSUE THREAD

**Issue by bonny** [ThemeAvenue/Plugin-Reviews#4]
I have my WordPress into a subdir called `/wp/` and the plugin does not work.

Error is:
```
PHP Warning:  require_once(/var/www/example.com/wp/wp/wp-admin/includes/plugin-install.php): failed to open stream: No such file or directory in /var/www/example.com/assets/plugins/plugin-reviews/class-wr-wordpress-plugin.php on line 58
```

Note that is has two "wp" in the path.

I changed `class-wr-wordpress-plugin.php` line 58 from 
```require_once( $admin_path . 'includes/plugin-install.php' );```
to
```require_once( ABSPATH . 'wp-admin/includes/plugin-install.php' );```

and now it works. Maybe there is a reason why `ABSPATH` is not used directly that I don't understand :)

**Comment by SiamKreative** [comment]
Thanks for reporting this. We'll look into it asap ;)

**Comment by julien731** [comment]
Hey @bonny ! Long time you opened this issue... I need to ask you one question: do you mean your site is accessed through the TLD (eg. domain.com) but installed in a sub-folder, or is your site accessed through the sub-dfolder directly (eg. domain.com/wp)?

**Comment by bonny** [comment]
hi! yep, the site with the plugin in action is here:
http://simple-history.com/
and the wp-admin is location here
http://simple-history.com/wp/wp-admin/
i.e. wordpress is installed in /wp/, not at the root /
