### ISSUE TITLE
Add option to ignore reviews from specific users

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/Plugin-Reviews#5]
If some cases, we might want to ignore comments from specific users! For instance, an user that left a bad review, change its rating to a good one, then forgot to change the review itself.

Example:
![image](https://cloud.githubusercontent.com/assets/1778633/8617729/dc708922-2730-11e5-902e-1c450722b1ad.png)

**Comment by julien731** [comment]
This is weird anyways. There must be something going wrong with the WP.org
API. You can see the review title has changed as well as the rating, only
the content is still the old one.

*---*
*Julien Liabeuf*
WordPress Specialist
http://julienliabeuf.com || GitHub <https://github.com/julien731> || Twitter
<https://twitter.com/julien731>
+66(0)8-7703-0926

**Comment by SiamKreative** [comment]
Also, as there is no option panel for this plugin, we should probably add the ability to clear the reviews cache. For instance, when we visit a specific link such as `http://getawesomesupport.dev/reviews/?reviews=clear`, it will clear the cache. In addition, we could add it to the topbar "Clear reviews cache".
